export const tastingNotes = [
  {
    id: 1,
    title: '발렌타인 30년 블렌디드 스카치 위스키',
    author: '닉네임',
    likes: 459,
    views: 2025,
    avatarUrl: '/images/avatar.png',
    comments: 72,
    imageUrl: '/images/whisky.png',
  },
  {
    id: 2,
    title: '발렌타인 30년 블렌디드 스카치 위스키',
    author: '닉네임',
    likes: 459,
    views: 2025,
    avatarUrl: '/images/avatar.png',
    comments: 72,
    imageUrl: '/images/whisky.png',
  },
  {
    id: 3,
    title: '발렌타인 30년 블렌디드 스카치 위스키',
    author: '닉네임',
    likes: 459,
    views: 2025,
    avatarUrl: '/images/avatar.png',
    comments: 72,
    imageUrl: '/images/whisky.png',
  },
  {
    id: 4,
    title: '발렌타인 30년 블렌디드 스카치 위스키',
    author: '닉네임',
    likes: 459,
    views: 2025,
    avatarUrl: '/images/avatar.png',
    comments: 72,
    imageUrl: '/images/whisky.png',
  },
  {
    id: 5,
    title: '발렌타인 30년 블렌디드 스카치 위스키',
    author: '닉네임',
    likes: 459,
    views: 2025,
    avatarUrl: '/images/avatar.png',
    comments: 72,
    imageUrl: '/images/whisky.png',
  },
  {
    id: 6,
    title: '발렌타인 30년 블렌디드 스카치 위스키',
    author: '닉네임',
    likes: 459,
    views: 2025,
    avatarUrl: '/images/avatar.png',
    comments: 72,
    imageUrl: '/images/whisky.png',
  },
];

export const communityPosts = [
  { id: 1, title: '입문자를 위한 위스키 추천 5선 (ft. 가성비 최고)' },
  { id: 2, title: '요즘 빠진 조합: 아벨라워 + 다크초콜릿, 미쳤어요' },
  { id: 3, title: '술풀할 때 듣는 재즈 플레이리스트 공유해요♪' },
  { id: 4, title: '[후기] 드디어 발베니 21년 오픈했습니다... 눈물남' },
  { id: 5, title: '여러분은 아이스볼 VS 온더락, 뭐 선호하시나요?' },
  { id: 6, title: '한국에서 구할 수 있는 독특한 증류주 추천해요!' },
  { id: 7, title: '칼데벳도 좋지만, 스트레이트 한잔의 여운이란...' },
  { id: 8, title: '입문 6개월 차, 테이스팅노트 어떻게 쓰고 계신가요?' },
  { id: 9, title: '술 마실 때 이런 안주 조합 추천합니다🔥' },
  { id: 10, title: '[토론] 위스키에도 계절이 있나요? 여름엔 애플리느 위스키는..' },
];

export const alcohols = [
  {
    id: 1,
    name: '발렌타인 30년 블렌디드 스카치 위스키',
    imageUrl: '/images/whisky.png',
    lgCategory: '위스키',
    smCategory: '블렌디드 위스키',
    region: '스코틀랜드',
    abv: '40',
    volume: '700ml',
    distillery: '발렌타인',
    rating: 3.8,
  },
];

export const communityPostsDetail = [
  {
    id: '1',
    title: '글렌피딕 12년 처음 마셔봄',
    authorId: 1,
    author: 'Alice',
    createdAt: '2025.07.22. 2:15',
    views: 372,
    postLikes: 4,
    commentsCount: 21,
    content:
      '위스키에 진짜 관심 하나도 없다가, 최근에 지인이 글렌피딕 12년을 선물해줘서 처음 마셔봤어요.',
  },
  {
    id: '2',
    title: '글렌피딕 12년 개별로',
    authorId: 2,
    author: 'Bob',
    createdAt: '2025.07.24. 2:15',
    views: 72,
    postLikes: 20,
    commentsCount: 30,
    content: '글렌피딕 붐따~',
  },
];
